name: Feature Request
description: Suggest a new feature
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: textarea
    id: need
    attributes:
      label: Need
      description: Explain the need
      placeholder: Why is this feature useful
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      placeholder: Describe the feature
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      placeholder: Add context if needed